Feature updates
alxdrcirilo/RamachanDraw pull request #7
Opened 2024-02-20 14:13 UTC by Aquaplant

Overall: made more comfortable usage and preventing output console prints, if unwanted by user

Added:
 - new functions for better user-experience
 - parameters to existing functions to prevent warnings from PDB structure parser, fetching prints and made print of table of ignored residues optional

Updated:
- function documentation, changed some variable names for better comprehension, added parameter types
- outsourced some nested function for module-use
- wrapped resource stream (hopefully prevents IO warnings caused by unclosed stream)
- changed plot title / legend titles to file-name only
- README (to match actual changes)

Feedback is appreciated.

2024-02-20 14:34 UTC, Aquaplant commented
Forgot to update module version

2024-02-20 19:51 UTC, alxdrcirilo requested changes
Thanks for deciding to contribute!

Let's first merge this into the `dev` branch once the comments are resolved and the respective changes pushed.

I plan to dust off this project and modernize it a bit in the coming weeks. These changes will be included on top of the `dev` branch as well and merged together with your changes to `master` once everything is ready.

Good work! 👍

2024-02-20 19:51 UTC, alxdrcirilo commented on RamachanDraw/fetch.py
> +from os import sep
`sep` is never used, you can remove this line.

2024-02-20 19:51 UTC, alxdrcirilo commented on RamachanDraw/fetch.py
> +from os.path import exists, realpath, basename
`basename` is never used, you can drop its import.

2024-02-20 19:51 UTC, alxdrcirilo commented on RamachanDraw/phi_psi.py
> +from os.path import exists, realpath
These are never used, you can remove this line.

2024-02-20 19:51 UTC, alxdrcirilo commented on RamachanDraw/phi_psi.py
> +def get_ignored_res(pdb_file_path: str, ignore_pdb_warnings: bool = False) -> (dict, list, list, list):
Can you change the return type hint to `tuple[dict, list, list, list]` please?

2024-02-20 19:51 UTC, alxdrcirilo commented on RamachanDraw/plot.py
> +         ignore_pdb_warnings: bool = False) -> (plt.Axes, dict):
Can you change the return type hint to `tuple[plt.Axes, dict]` please?

2024-02-20 19:51 UTC, alxdrcirilo commented on RamachanDraw/plot.py
> +    return tuple(path_out)
This is a nice feature! :)

There may be a nicer way to do this, but for now it seems to get the job done.

2024-02-22 09:17 UTC, alxdrcirilo approved these changes

2024-02-22 09:18 UTC, merged